# Workflow Resources
helpdesk_member_workflow_collection:
    path:     /workflows
    controller: Webkul\UVDesk\AutomationBundle\Controller\Automations\Workflow::listWorkflowCollection
    defaults: { panelId: 'productivity' }
    
workflowslist_xhr:
    path:     /workflows/xhr
    controller: Webkul\UVDesk\AutomationBundle\Controller\Automations\WorkflowXHR::workflowsListXhr
    defaults: { panelId: 'productivity' }

workflows_addaction:
    path:     /workflow/add
    controller: Webkul\UVDesk\AutomationBundle\Controller\Automations\Workflow::createWorkflow
    defaults: { panelId: 'productivity' }

workflows_editaction:
    path:     /workflow/edit/{id}
    controller: Webkul\UVDesk\AutomationBundle\Controller\Automations\Workflow::editWorkflow
    defaults: { panelId: 'productivity'}

workflows_xhraction:
    path:     /workflow-ajax/{id}
    controller: Webkul\UVDesk\AutomationBundle\Controller\Automations\WorkflowXHR::WorkflowsxhrAction
    defaults: { panelId: 'productivity', id: 0 }

helpdesk_member_workflow_condition_options_xhr:
    path:     /workflow/xhr/condition/options/{entity}
    controller: Webkul\UVDesk\AutomationBundle\Controller\Automations\WorkflowXHR::getWorkflowConditionOptionsXHR
    defaults:   { entity: default }

helpdesk_member_workflow_action_options_xhr:
    path:     /workflow/xhr/action/options/{entity}/{event}
    controller: Webkul\UVDesk\AutomationBundle\Controller\Automations\WorkflowXHR::getWorkflowActionOptionsXHR
    defaults:   { entity: default , event: null}
